### ISSUE TITLE
Dev Env Rudolf einrichten

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-backlog#30]
Für das Ausführen und Entwickeln der prox-* Projekte müssen folgende Programme installiert und eingerichtet sein:

- IntelliJ IDEA
- Docker for Windows

Außerdem soll eine docker-compose Datei erstellt werden, mit der die komplete prox-Umgebung lokal hochgefahren wird.

**Comment by rudolfgrauberger** [comment]
IntelliJ und Docker waren bereits installiert.

Beim Auseinandersetzen für die Umsetzung der docker-compose Datei habe ich festgestellt, dass wenn die Umgebung mit einem Befehl hochgefahren wird erstmal noch nichts gewonnen ist. Inbesondere da man im Moment das prox-web-client nicht als Docker-Container starten kann bzw. das schon geht, aber dann die Services Online benutzt werden und nicht die, die lokal laufen.

Aus diesem Grund habe ich in dem Repository [prox-local-setup](https://github.com/Archi-Lab/prox-local-setup) eine Anleitung erstellt, mit der der Erstkontakt mit dem Prox-Projekt hoffentlich etwas einfacher wird.
