### ISSUE TITLE
Umzug von ArchiLab Software auf entsprechende VMs

### ISSUE THREAD

**Issue by jlengelsen** [Archi-Lab/prox-backlog#34]
archilab-infra: Nexus, Jenkins, SonarQube, Keycloak
archilab-atlassian: Confluence, Jira
coalbase-prod: Produktiv-Version von Coalbase
coalbase-dev: Development-Version von Coalbase
prox-prod: Produktiv-Version von Prox
prox-dev: Development-Version von Prox
prox-build: vorübergehender Jenkins

**Comment by stefanbente** [comment]
Mit Doku in prox-doku
