### ISSUE TITLE
Dokumentation Clean-Code-Regeln

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-backlog#40]
* alles Englisch
* Namenskonventionen dokumentieren
* existierenden Code nachziehen

**Comment by rudolfgrauberger** [comment]
Ich habe unter https://www.archi-lab.io/pages/viewpage.action?pageId=17268737 die erste Version davon erstellt. Dafür habe ich den aktuellen Stand von https://github.com/Archi-Lab/prox-project-service und https://github.com/Archi-Lab/prox-module-service als Basis genommen.
