### ISSUE TITLE
Umstellung aller coalbase-Projekte auf Docker Agent

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-backlog#44]
Genauso umstellen, wie das für Prox schon passiert ist. 

**Bitte jeweils einen eigenen entsprechenden Task für jedes coalbase-Projekt anlegen**

**Comment by rudolfgrauberger** [comment]
Habe einzelne Tasks (#60, #61, #62, #63, #64, #65, #66, #67, #68) für die coalbase-Projekte angelegt
