### ISSUE TITLE
Neues eigenes Repo für Jenkins anlegen

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-backlog#45]

**Comment by stefanbente** [comment]
Bitte noch eigene Tasks fpr Keycloak, Sonarqube, Nexus etc. anlegen

**Comment by rudolfgrauberger** [comment]
Ich habe sehr viel lokal gearbeitet und es immer auf meinem PC validiert. Ich habe GitHub als Server benutzt um zwischen den Systemen zu synchronisieren. Das habe ich erstmal in einem [privaten Repository](https://github.com/rudolfgrauberger/archilab-jenkins-infrastructure) gemacht und werde es nach Absprache/Abstimmung mit @jlengelsen dann in die Organisation umziehen/verschieben.

**Comment by rudolfgrauberger** [comment]
Ich würde als Prefix für Infrastruktur-Projekte "infrastructure-" vorschlagen, das wäre für Jenkins dann "infrastructure-jenkins".

**Comment by rudolfgrauberger** [comment]
@jlengelsen hat das Repository angelegt und mein Repository vom Inhalt und Historie übernommen.
