### ISSUE TITLE
Alle Pipelines neu konfigurieren

### ISSUE THREAD

**Issue by jlengelsen** [Archi-Lab/prox-backlog#81]
- Scripted Pipelines mit Docker Agents

**Comment by rudolfgrauberger** [comment]
Ich habe auf die Arbeit von @jlengelsen aufgebaut und habe erst mal https://github.com/Archi-Lab/prox-service-discovery so umgestellt, dass das Bauen und Pushen des Images funktioniert.

Ich habe es leider nicht optimal umsetzen können, da uns aber etwas die Zeit davon läuft (Guided Projects) habe ich mich dazu entschieden, dass erstmal zum Funktionieren zu bringen.

Für Optimierungen bzw. Verbesserung können wir uns nachher noch Zeit nehmen, wenn uns die Zeit dazu gegeben wird.

**Comment by rudolfgrauberger** [comment]
Anschließend habe ich die nachfolgende Projekte im Branch `jenkins-migration` genauso umgestellt:
- [prox-api-gateway](https://github.com/Archi-Lab/prox-api-gateway/tree/jenkins-migration)
- [prox-module-service](https://github.com/Archi-Lab/prox-module-service/tree/jenkins-migration)
- [prox-project-service](https://github.com/Archi-Lab/prox-project-service/tree/jenkins-migration)
- [prox-web-client](https://github.com/Archi-Lab/prox-web-client/tree/jenkins-migration)

Das Repository von `prox-proposal-service` habe ich so gelassen wie es ist, da ich nicht genau weiß was alles Notentechnisch relevant ist.

**Comment by rudolfgrauberger** [comment]
Aktuell lassen sich alle Projekte von dem neuen Jenkins unter https://build2.archi-lab.io/ fehlerfrei bauen und auch das Deployen auf die **prox-prod2** docker-machine funktioniert.

Da ich leider so kurzfristig keinen Zugang zu dem Prox-Server hatte, habe ich mit curl die folgenden Services getestet:
- web-client -> curl 10.10.10.41:9090
- project-service -> curl 10.10.10.41:8081/projects
- module-service -> curl 10.10.10.41:8081/modules
- api-gateway -> curl 10.10.10.41:8081/actuator

Wenn das Routing jetzt noch im Proxy für https://prox2.archi-lab.io/ auf **prox-prod2** geändert wird, dann sollte - soweit ich es testen konnte - das funktionieren.

**Comment by rudolfgrauberger** [comment]
Ich habe in dem README-Dateien in dem Branch `jenkins-migration` der jeweiligen Repositories die  Schritte und wie man es benutzt angepasst.
