### ISSUE TITLE
Eigene VM für Expose-PP, mit Merge der aktuellen Änderungen aus dem Main-Branch

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-backlog#89]

**Comment by stefanbente** [comment]
Pair-Programming Rudolf-Julian

**Comment by rudolfgrauberger** [comment]
Es gibt nun die pp-ss2019-Umgebung, dazu gehören:
- VM `prox-pp-ss2019`/10.10.10.44
- Docker-Machine `prox-pp-ss2019`
- Pipelines
- URLs https://pp-ss2019.prox.archi-lab.io und https://api.pp-ss2019.prox.archi-lab.io/

Damit ist die komplette Umgebung für das Praxis-Projekt eingerichtet und sobald auf einen der Branches gepushed wird, wird die Version auch automatisch dahin deployed.
