### ISSUE TITLE
 Dokumentation in GitHub bündeln, z.B. in archilab-documentation

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-backlog#90]

**Comment by rudolfgrauberger** [comment]
Ich habe im [Prox-Wiki](https://github.com/Archi-Lab/prox-documentation/wiki) auf der Home-Seite einige allgemeine Informationen wie z. B. das Branching-Modell und die Namenskonventionen hinzugefügt.

**Comment by rudolfgrauberger** [comment]
Außerdem habe ich das Repository und darin das Wiki [archilab-documentation](https://github.com/Archi-Lab/archilab-documentation/wiki) angelegt. Ich habe die projektspezifische Dokumentationen zu Prox und Coalbase sowie Links zu den Globalen archilab-Repositories (jenkins, backup, graylog und pre-commit-hooks) hinzugefügt.
